import java.awt.Color;
import java.util.*;
import java.sql.*;
import javax.swing.JOptionPane;

public class AdminGetDetails extends javax.swing.JFrame {
 ArrayList<Cart> al;
  
    public  AdminGetDetails(ArrayList<Cart> al) 
    {   
        initComponents();
        this.al=al;
        setSize(574,355);
        setLocationRelativeTo(null);
        setVisible(true);
        getContentPane().setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Fill Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 20, 140, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Customer Phone Number:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 190, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mode of Payment:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 140, 160, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 104, 250, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Do Payment", "Cash", "Online" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(260, 150, 250, 26);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Do Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 220, 220, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String phoneNumber=jTextField1.getText();
        String mop=jComboBox1.getSelectedItem().toString();
        int billid=0;
        try
        {
        ResultSet rs=DBloader.executeQuery("select * from bill","pos2024");
        
        rs.moveToInsertRow();
        rs.updateString("gtotal", Global.gtotal+"");
        rs.updateString("adminemail", Global.adminemail);
        rs.updateString("phoneno",phoneNumber);
        rs.updateString("paymenttype",mop);
        rs.insertRow();
        ResultSet rs2=DBloader.executeQuery("select MAX(billid) as billid from bill","pos2024");
        if(rs2.next())
        {
            billid=rs2.getInt("billid");
            
        }
         ResultSet rs3=DBloader.executeQuery("select * from billdetails", "pos2024");
         for(int i=0; i<al.size();i++)
         {
             rs3.moveToInsertRow();
             
             rs3.updateInt("billid", billid);
             rs3.updateString("pname", al.get(i).productname);
             rs3.updateInt("offerprice",al.get(i).offerprice);
             rs3.updateInt("quantity",al.get(i).quantity);
             rs3.insertRow();
         }
         JOptionPane.showMessageDialog(this,"bill generated succesfully");
         
        }
        catch(Exception ex)
                {
                ex.printStackTrace();
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGetDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGetDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGetDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGetDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGetDetails(al).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
