
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

public class AdminManageProducts extends javax.swing.JFrame {
    Vector<String> vl;
    ArrayList<Products>al;
    mytablemodel tm;
    
    public AdminManageProducts() {
        vl=new Vector<>();
        al=new ArrayList<>();
        tm=new mytablemodel();
         initComponents();
         jTable1.setModel(tm);
         ShowAlreadyAddedProducts();
       adminShowDropdown();
         Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
         getContentPane().setBackground(Color.PINK);
       jComboBox2.setModel(new DefaultComboBoxModel<>(vl));
        int width=(int) d.getWidth();
        int height=(int) d.getHeight();
        setSize(width,height);
        setVisible(true);
    }
    int count;
    void ShowAlreadyAddedProducts()
    {
        try
        {
    ResultSet rs=   DBloader.executeQuery("select * from products", "pos2024");
    al.clear();
       while(rs.next())
       {   count++;
           String productname=rs.getString("productname");
           String desc=rs.getString("desc");
           String catname=rs.getString("category");
           int offerprice=rs.getInt("offerprice");
           int quantity=rs.getInt("quantity");
           
           al.add(new Products(productname,desc,catname,offerprice,quantity));
       }
    tm.fireTableDataChanged();
    
    }
        
    catch(Exception ex)
    {
        ex.printStackTrace();
    }
    }
     class mytablemodel extends AbstractTableModel
    {

        @Override
        public int getRowCount() {
            return al.size();
             
        }

        @Override
        public int getColumnCount() {
            return 5;
           
        }

        @Override
        public Object getValueAt(int i, int j) {
           Products obj= al.get(i);
           if(j==0)
           {
           return obj.productname;
           }
           else if(j==1)
           {
            return obj.desc;
        }
           else if(j==2)
           {
               return obj.catname;
           }
           else if(j==3)
           {
               return obj.offerprice;
           }
           else if(j==4)
           {
               return obj.quantity;
           }
           return null;
    }
        @Override
        public String getColumnName(int j)
        {
            String col[]={"Product Name","Description","Category Name","Offer Price","Quantity"};
            return col[j];
        }
            
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manage Your Products");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 10, 290, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Add Products");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 50, 150, 40);

        jLabel3.setText("Product Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 110, 110, 20);

        jLabel4.setText("Description:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 160, 90, 20);

        jLabel5.setText("Photo:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 290, 80, 40);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 300, 140, 110);

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 300, 76, 40);

        jLabel7.setText("Category:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 410, 80, 20);

        jLabel8.setText("Price:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 460, 70, 30);

        jLabel9.setText("Offer Price:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 510, 100, 20);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 600, 190, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 110, 210, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 460, 190, 26);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 160, 210, 106);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(220, 410, 190, 26);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 510, 190, 30);

        jLabel10.setText("Quantity:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 560, 80, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(220, 560, 190, 26);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("       View Products");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(860, 50, 210, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(722, 100, 480, 480);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(930, 600, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static BufferedImage scale(BufferedImage src, int w, int h)
{
    BufferedImage img = 
            new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
    int x, y;
    int ww = src.getWidth();
    int hh = src.getHeight();
    int[] ys = new int[h];
    for (y = 0; y < h; y++)
        ys[y] = y * hh / h;
    for (x = 0; x < w; x++) {
        int newX = x * ww / w;
        for (y = 0; y < h; y++) {
            int col = src.getRGB(newX, ys[y]);
            img.setRGB(x, y, col);
        }
    }
    return img;
}
    
    
    
    File selectedfile;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //action on click on choose button
         int ans= jFileChooser1.showOpenDialog(this);
       if(ans==JFileChooser.APPROVE_OPTION)
       {
         selectedfile=jFileChooser1.getSelectedFile();
        
         try
         {
              BufferedImage bi = ImageIO.read(selectedfile);
                
                bi = scale(bi,jLabel6.getWidth(), jLabel6.getHeight());
                
                jLabel6.setIcon(new ImageIcon(bi));
             
             
         }
         catch(Exception ex)
         {
             ex.printStackTrace();
         }
           String selected = null;
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String productname=jTextField1.getText();
        String desc=jTextArea1.getText();
        int price=Integer.parseInt(jTextField3.getText());
         int offerprice=Integer.parseInt(jTextField2.getText());
        String category=(String) jComboBox2.getSelectedItem();
        int quantity=Integer.parseInt(jTextField4.getText());
        
        try
        {
        ResultSet rs=DBloader.executeQuery("select * from products where productname='"+productname+"'", "pos2024");
        if(rs.next())
        {
            JOptionPane.showMessageDialog(this,"product already exists");
        }
        else
        {
            String path=SaveFile.saveFile(selectedfile);
            rs.moveToInsertRow();
            rs.updateString("productname",productname);
            rs.updateString("desc",desc);
            rs.updateString("photo",path);
            rs.updateInt("price",price);
            rs.updateInt("offerprice",offerprice);
            rs.updateString("category",category);
            rs.updateInt("quantity",quantity);
            
            
            rs.insertRow();
            JOptionPane.showMessageDialog(this, "Product added successfully");
            ShowAlreadyAddedProducts();
        }
        }
        catch(Exception ex)
         {
             ex.printStackTrace();
                    
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         int column=0;
        int row=jTable1.getSelectedRow();
        String productname=(String) jTable1.getModel().getValueAt(row, column);
        try{
        ResultSet rs= DBloader.executeQuery("select * from products where productname= '" +productname+"'","pos2024");
       if(rs.next())
       {
           rs.deleteRow();
           ShowAlreadyAddedProducts();
           JOptionPane.showMessageDialog(this,"Category Deleted Successfully");
           
       }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
   void adminShowDropdown()
    {
        try{
        ResultSet rs=DBloader.executeQuery("select catname from categories", "pos2024");
    
        while(rs.next())
        {
            String catname=rs.getString("catname");
            vl.add(catname);
            
            
            
         
        }
        }
        catch(Exception ex)
        {
        
        ex.printStackTrace();
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            { 
                new AdminManageProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
