import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
public class Change_Password extends javax.swing.JFrame {

    /**
     * Creates new form Change_Password
     */
    public Change_Password() {
        initComponents();
        getContentPane().setBackground(Color.PINK);
        setSize(607,355);
        setLocationRelativeTo(null);
        setTitle("Change Password");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pf1 = new javax.swing.JPasswordField();
        pf2 = new javax.swing.JPasswordField();
        pf3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Change Your Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(151, 12, 337, 37);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Old Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(65, 67, 143, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("New Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 172, 44);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Confirm New Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 190, 164, 38);
        getContentPane().add(pf1);
        pf1.setBounds(288, 67, 165, 26);
        getContentPane().add(pf2);
        pf2.setBounds(290, 130, 165, 26);

        pf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf3ActionPerformed(evt);
            }
        });
        getContentPane().add(pf3);
        pf3.setBounds(290, 190, 165, 26);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 250, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String oldPassword = pf1.getText();
        String newPassword=pf2.getText();
        String confirmNewPassword=pf3.getText();
        String email=Global.adminemail;
        if(newPassword.equals(confirmNewPassword))
        {
            
            try{
          ResultSet rs=DBloader.executeQuery("select *from admin where email='"+email+"' and password='"+oldPassword+"'", "pos2024");
          if(rs.next())
              
          {
              rs.updateString("password",newPassword);
              rs.updateRow();//new data filled
              JOptionPane.showMessageDialog(this, "Password Change Successful");      
              dispose();
              AdminLogin obj=new AdminLogin();
          }
            else
            {
               JOptionPane.showMessageDialog(this,"Incorrect Old Password");     }
            }
        catch(Exception ex)
        {
                ex.printStackTrace();
        }
        }
                
        else
        {
        JOptionPane.showMessageDialog(this, "New Password & Confirm New Password Does Not Match");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JPasswordField pf2;
    private javax.swing.JPasswordField pf3;
    // End of variables declaration//GEN-END:variables
}
